build.sh
when the `GOOS` and `GOARCH` environment variable do not exist
the `build.sh` script echo `polaris-server-release_v1.0.1..`
`if [ -n $GOOS ] && [ -n $GOARCH ]` should be replace by `if [ -n "$GOOS" ] && [ -n "$GOARCH" ]`
=> add "" to judge whether the environment variable exists"

build.sh
There is an error in build.sh, when run it I got the error message: 
```
./build.sh: line 8: [: ==: unary operator expected
./build.sh: line 11: [: ==: unary operator expected
./build.sh: line 16: [: ==: unary operator expected
GOOS is , binary name is polaris-server
adding: polaris-server-release_v1.2.1../ (stored 0%)
adding: polaris-server-release_v1.2.1../tool/ (stored 0%)
adding: polaris-server-release_v1.2.1../tool/check.sh (deflated 50%)
adding: polaris-server-release_v1.2.1../tool/start.bat (deflated 53%)
adding: polaris-server-release_v1.2.1../tool/reload.sh (deflated 52%)
adding: polaris-server-release_v1.2.1../tool/start.sh (deflated 50%)
adding: polaris-server-release_v1.2.1../tool/p.sh (deflated 51%)
adding: polaris-server-release_v1.2.1../tool/stop.bat (deflated 41%)
adding: …
```
=> Fix script error

go.mod, go.sum, main.go
**Please provide issue(s) of this PR:**https://github.com/polarismesh/polaris/issues/181
GOMAXPROCS需要根据实际CPU配额进行设置，特别是在有CPU限制的容器环境中，Golang 服务默认会拿宿主机的 CPU 核心数来调用 runtime.GOMAXPROCS()，可能导致 P 数量远远大于可用的 CPU 核心，引起频繁上下文切换，影响高负载情况下的服务性能 。“go.uber.org/automaxprocs”可以根据环境自动设置GOMAXPROCS。
=> feat:setting GOMAXPROCS according to real CPU quota

common/connlimit/listener.go
**Please provide issue(s) of this PR:
Optimize the use of locks，distinguish between read lock and write lock.
=> perf:use sync.RWMutex replace sync.Mutex in counter

naming/cache/instance.go, naming/cache/service.go, naming/namespace.go
Fixes #https://github.com/polarismesh/polaris/issues/157
namespace 能被删除的其中一个前提是对应的service 已经全部被删除了，但service被删除的时候service对应的内存地址空间没有清除，所以在删除namespace 的时候顺带清除对应的内存。
=> [ISSUE#157]fix:clean namespace's servicecache when delete namespace

apiserver/httpserver/console_access.go
=> fix: console_access.go interface response structure, use handler.WriteHeaderAndProto replace handler.WriteHeader

common/connlimit/listener_test.go, common/redispool/redis_pool.go, plugin/auth/platform/platform.go, service/healthcheck/check.go, service/healthcheck/server.go, service/test/instance_test.go
Fixes https://github.com/polarismesh/polaris/issues/223
use for range instead of for { select {} };
use a simple channel send/receive instand of  `select ` with a single case
select 监听单一channel时，在go实现层面编译器会将 select 改写成 if 条件语句
可参考下面这边blog 的介绍
https://draveness.me/golang/docs/part2-foundation/ch05-keyword/golang-select/ 
根据golangci-lint 的检测提示，可以将检测出的case 修改成 从channel中阻塞读取，功能上等价
=> style:use range instead of select

service/utils.go
=> fix: port值为0时判定为empty

README-zh.md, README.md
=> docs:update info of spring cloud integrates with polaris-java.

config/event.go, config/event_test.go
refactor event watch
```go
type Center struct {
watchers *sync.Map
lock     *sync.Mutex
}
```
The original Event Watch uses sync Map and sync Mutex mixed mode, which is a misuse of sync. mutex and sync. map. In fact, the event Watch design only needs to be implemented by map+ RWLock, which looks simple and clear. Easier maintenance.
=> feat: event watch refactor use map with rwlock

common/redispool/redis_pool.go, deploy/helm/templates/polaris-server-config.yaml, deploy/standalone/k8s/02-polaris-server-config.yaml, polaris-server.yaml, test/discover/test.yaml
Fixes #404 
- removed `maxIdle` option of redis
- added `poolSize` and `minIdleConns` options of redis
- updated yaml and helm templates, default `poolSize` is 200 and default `minIdleConns` is 30
=> feat: add redis options of minIdleConns and poolSize

store/sqldb/scripts/delta/v160-v170.sql, store/sqldb/scripts/delta/v170-v180.sql, store/sqldb/scripts/polaris_server.sql
=> 修改CHARSET = utf8mb4 COLLATE = utf8mb4_bin;

apiserver/httpserver/config_server.go, apiserver/httpserver/config_server_apidoc.go, apiserver/httpserver/naming_client_access.go, apiserver/httpserver/naming_console_access.go, apiserver/httpserver/swagger_access.go, go.mod, go.sum
=> config_server中的http接口添加Swagger的描述

namespace/default.go, namespace/namespace.go, namespace/namespace_authability.go, namespace/server.go, namespace/server_authability.go, namespace/test_export.go
Fixes https://github.com/polarismesh/polaris/issues/731
update namespace for code style
=> feat: update namespace for code style

apiserver/xdsserverv3/server.go
=> feat: 修复正则表达式不生效问题

deploy/helm/templates/polaris-server.yaml
polaris 集群模式副本数当前默认为1，调整为取值{{ .Values.polaris.replicaCount }}
Fixes #
=> polaris 集群模式副本数取值错误问题

apiserver/eurekaserver/access.go, apiserver/eurekaserver/replicate.go
=> feat：修复polaris之间走eureka同步接口出现报错的问题

apiserver/httpserver/config_console_access.go, apiserver/httpserver/config_server.go, apiserver/httpserver/config_server_apidoc.go, apiserver/httpserver/http/handler.go, common/api/v1/config_file_response_build.go, common/utils/config_file.go, config/api.go, config/bootstrap_test.go, config/config_file.go, config/config_file_authibility.go, config/config_file_group.go, config/config_file_test.go, go.mod, go.sum, store/mock/api_mock.go, store/mysql/config_file.go, test/config_file_test.go, test/http/client.go, test/http/config_center.go, test/resource/config_center.go
=> feat: 配置文件导入导出功能 (#524)

cache/default.go, cache/strategy.go, cache/user.go, cache/user_test.go
=> fix:存储层出现问题可能导致cache数据更新阻塞

apiserver/eurekaserver/write.go, service/api_v1.go, service/client_v1_authability.go, service/instance.go, service/instance_test.go
=> fix: eureka updateStatus鉴权失败

apiserver/httpserver/i18n/translate.go, bootstrap/server.go, cache/faultdetect.go, common/utils/const.go, service/faultdetect_config_test.go, service/healthcheck/server.go
=> fix: 解决健康检查规则打印时候出现的协程panic问题

apiserver/eurekaserver/access.go, apiserver/eurekaserver/applications.go, apiserver/eurekaserver/config.go, apiserver/eurekaserver/replicate.go, apiserver/eurekaserver/server.go, apiserver/eurekaserver/write.go, release/conf/polaris-server.yaml
=> 增强instanceId兼容性，调整status同步逻辑

bootstrap/config/config.go, bootstrap/server.go, go.mod, go.sum, maintain/config.go, maintain/default.go, maintain/job/clean_deleted_instance.go, maintain/job/config.go, maintain/job/delete_empty_service.go, maintain/job/delete_empty_service_test.go, maintain/job/delete_unhealthy_instance.go, maintain/job/delete_unhealthy_instance_test.go, maintain/job/job.go, maintain/maintain.go, release/conf/polaris-server.yaml, service/api_v1.go, service/instance.go, service/instance_authability.go, store/boltdb/maintain.go, store/boltdb/maintain_test.go, store/maintain_api.go, store/mock/api_mock.go, store/mysql/maintain.go
=> v1.15 add maintain job

apiserver/eurekaserver/access.go, apiserver/eurekaserver/applications.go, apiserver/eurekaserver/config.go, apiserver/eurekaserver/replicate.go, apiserver/eurekaserver/server.go, apiserver/eurekaserver/write.go, common/redispool/redis_pool.go, release/conf/polaris-server.yaml
- 增强instanceId兼容性，调整status同步逻辑 (https://github.com/polarismesh/polaris/pull/1018)
=> fix:合并main分支部分feature到release-v1.15.0

release/standalone/docker-compose/prometheus/prometheus.yml
fix prometheus.yml bug
the targets cannot start with  "http://"
Error logs:
ts=2023-04-13T09:21:39.900Z caller=main.go:434 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" err="parsing YAML file /etc/prometheus/prometheus.yml: \"http://localhost:9090\" is not a valid hostname"
Fixes #
=> Fix prometheus.yml bug

cache/config_file.go, config/bootstrap_test.go, config/client_config_file.go, config/config_file.go, config/config_file_test.go, config/utils/utils.go, config/watcher.go, go.mod, go.sum, plugin/crypto/aes/aes.go, plugin/crypto/aes/aes_test.go
=> 配置加密支持选择加密算法

.github/workflows/golangci-lint.yml, apiserver/eurekaserver/access.go, apiserver/grpcserver/config/client_access.go, apiserver/httpserver/config_client_access.go, apiserver/xdsserverv3/server.go, auth/defaultauth/auth_checker.go, auth/defaultauth/auth_checker_test.go, auth/defaultauth/common_test.go, auth/defaultauth/config.go, bootstrap/server.go, cache/cache.go, cache/routing_config.go, config/client_config_file.go, config/config_file.go, config/config_file_test.go, config/connection_manager.go, release/conf/i18n/en.toml, release/conf/polaris-server.yaml, service/circuitbreaker_rule_authability.go, service/healthcheck/cache.go, service/healthcheck/report.go, service/healthcheck/server.go, service/healthcheck/test_export.go
=> refactor:优化鉴权相关功能开关以及修复NPE问题

service/client_v1.go
spring cloud tencent discovery通过服务别名拉取时，拉取到的服务信息为源服务服务信息，未触发该服务别名服务发现事件，导致实际存在服务实例信息，实例列表却为空问题。
Fixes #1183
=> 修复通过服务别名拉取时，服务信息为源服务信息问题

store/mysql/default.go
=> feat: allow empty db password

apiserver/grpcserver/base.go
Fixes # 修复问题：grpc server handler 报错时会触发 recover 函数体中的日志；而真正 panic 时不会打 panic 日志
=> fix: 修复 grpc server panic 日志的 bug

release/conf/polaris-server.yaml, release/standalone/docker-compose/server/polaris-server.yaml, service/default.go, service/instance.go, service/server.go
=> feat:新增配置控制是否允许自动创建服务

apiserver/xdsserverv3/resource/help.go, apiserver/xdsserverv3/server.go
=> fix:xds rule build

apiserver/nacosserver/core/storage.go
=> 修复nacos服务发现clusters逻辑兼容问题

apiserver/httpserver/utils/handler.go, apiserver/httpserver/utils/handler_test.go, service/instance.go, service/instance_test.go
Fixes #
`/naming/v1/instances` 接口目前只支持查询一组 metadata 条件，我们希望支持可查询多组 metadata 条件，为此进行了如下修改：
1. 修改 `ParseQueryParams` 函数，当 query 里的 `keys` 和 `values` 有多个时，使用逗号将其拼接
2. 修改 `preGetInstances` 函数，使用逗号解析 `keys` 和 `values` 字段，并将其写入 map
=> feat: http实例查询接口支持多个metadata条件查询

release/README-zh.md
=> Fix the link and improve the new Chinese document.

release/cluster/helm/README-zh.md, release/cluster/helm/README.md, release/cluster/helm/templates/prometheus.yaml
Fixes https://github.com/polarismesh/polaris/issues/1401
=> chore: update helm files and README
