apiserver/l5pbserver/naming.go
apiserver/l5pbserver/server.go

fmt code and code style adjust

feat: fmt code and code style adjust

---

README-zh.md
README.md

polaris apiserver is listern on 8090

update README-zh.md README.md

---

config/config.go

fix: close config file

---

bootstrap/run_darwin.go
bootstrap/run_linux.go
bootstrap/run_windows.go
bootstrap/server.go

1. refactor bootstrap RunMainLoop and adjust singal chan to buf chan
2. go fmt code

feat: refactor bootstrap and code fmt

---

apiserver/httpserver/admin.go
apiserver/httpserver/client_access.go
apiserver/httpserver/console_access.go
apiserver/httpserver/default.go
apiserver/httpserver/handler.go
apiserver/httpserver/maintain_access.go
apiserver/httpserver/proto.go
apiserver/httpserver/server.go

1. adjust httpserver.HttpSever to HTTPServer
2. fix err.Error() panic

feat: adjust HttpServer to HTTPServer and fix err.Error() panic

---

standalone/install/install-darwin.sh

[ISSUE #38] fix install bug in mac env

---

config/config.go

code fmt for Config package

---

standalone/install/uninstall-darwin.sh
tool/include

[ISSUE #38] fix uninstall bug in mac

---

store/boltdbStore/business_test.go
store/boltdbStore/circuitbreaker.go
store/boltdbStore/circuitbreaker_test.go
store/boltdbStore/handler.go
store/boltdbStore/namespace.go
store/boltdbStore/platform_test.go
store/boltdbStore/service.go
store/status.go

[ISSUE #20] fix circuitbreaker for boltdb

---

bootstrap/server.go

remove duplicated code
https://github.com/polarismesh/polaris/blob/1e43499533d55937bc504720ea0436bc2375c937/bootstrap/server.go#L277

remove duplicated code

---

common/version/version.go

code fmt for version package

---

naming/circuitbreaker_config.go
naming/circuitbreaker_config_test.go
naming/client.go
naming/healthcheck.go
naming/instance.go
naming/l5_service.go
naming/namespace.go
naming/platform.go
naming/ratelimit_config.go
naming/ratelimit_config_test.go
naming/routing_config.go
naming/server.go
naming/service.go
naming/service_alias.go
naming/utils.go

go fmt for naming package

---

store/sql.go
store/status.go
store/store.go

go fmt for store package

---

plugin/auth.go
plugin/auth/platform/platform.go
plugin/cmdb.go
plugin/cmdb/memory/memeory.go
plugin/discoverstatis.go
plugin/history.go
plugin/history/logger/history_logger.go
plugin/parsePassword.go
plugin/parsePassword/parse.go
plugin/plugin.go
plugin/ratelimit.go
plugin/ratelimit/lrurate/base.go
plugin/ratelimit/lrurate/lrurate.go
plugin/ratelimit/lrurate/lrurate_test.go
plugin/statis.go
plugin/statis/local/apicall.go
plugin/statis/local/local.go
plugin/statis/local/logger.go

go fmt for plugin package code

go code for plugin package

---

common/utils/cl5.go
common/utils/const.go
common/utils/context.go
common/utils/funcs.go
common/utils/ptypes.go

code fmt for utils package

---

naming/auth/api.go
naming/auth/authority.go
naming/auth/mock/api_mock.go

1.fmt code
2.optimize auth package

go code fmt and optimize for auth package

---

common/model/instance.go
common/model/l5.go
common/model/naming.go

go code fmt for model and iota adjust

code fmt for model and const iota adjust

---

naming/cache/cache.go
naming/cache/cache_test.go
naming/cache/circuitbreaker_config.go
naming/cache/circuitbreaker_config_test.go
naming/cache/config.go
naming/cache/instance.go
naming/cache/instance_test.go
naming/cache/l5.go
naming/cache/ratelimit_config.go
naming/cache/ratelimit_config_test.go
naming/cache/routing_config.go
naming/cache/service.go
naming/cache/service_test.go

code fmt for naming/cache package

code fmt for naming/cache and optimize ComputeRevision func

---

polaris-server.yaml
store/boltdbStore/namespace.go

feat: remove l5protocol in default config file

---

apiserver/grpcserver/server.go
apiserver/httpserver/server.go
common/connlimit/api.go
common/connlimit/config.go
common/connlimit/config_test.go
common/connlimit/conn.go
common/connlimit/listener.go
common/connlimit/listener_test.go
common/connlimit/mock_net/mock_conn.go
common/connlimit/stats.go

1. code fmt for connlimit
2. optimize logic

code fmt and optimize connlimit

---

common/ckv/ckv_test.go
common/ckv/ckvpool.go
common/ckv/conn.go

refactor ckv and fmt code

---

common/redispool/redis_pool.go

code fmt for redis pool and optimize code

---

common/timewheel/timewheel.go

code fmt and optimize timewheel

code fmt and optimize timewheel logic

---

naming/batch/batch.go
naming/batch/batch_test.go
naming/batch/config.go
naming/batch/future.go
naming/batch/instance.go
naming/batch/utils.go

code fmt and optimize code logic

code fmt for naming/batch package and optimize naming/batch code

---

common/utils/funcs.go
store/boltdbStore/service.go
store/boltdbStore/service_test.go
store/defaultStore/sql.go

fix boltdb didn't support fuzzy query.
fixes #98

Fix fuzzy query problem in boltdb

---

.golangci.yml
apiserver/httpserver/maintain_access.go
naming/batch/future.go
naming/batch/instance.go
naming/cache/cache.go
naming/cache/circuitbreaker_config.go
naming/cache/ratelimit_config.go
naming/cache/routing_config.go

golangci-lint identifies many issues on the codebase. Fixes some of them.
Please consider add this to contribution guide and enforce that on every upcoming PRs.

Introduce golangci-lint and fix some issues

---

.github/pull_request_template.md

feat: remove unnecessary components

---

.github/workflows/standalone.yml

feat: change standalone relative path

---

build.sh
build_cmdb.sh
build_docker.sh

[ISSUE #133] refactor: refactor build script

---

store/boltdb/default.go
store/boltdb/handler.go
store/boltdb/namespace_test.go
store/boltdb/transaction.go

fix:  internal boltdb deadlock

---

plugin/healthchecker/heartbeatmemory/checker_memory.go
plugin/healthchecker/heartbeatmemory/checker_memory_test.go

**Please provide issue(s) of this PR:
Fixes #142 

fix: MemoryHealthChecker do query will panic

---

common/log/config.go

如果配置文件中`OutputPaths`或者`ErrorOutputPaths`是使用本地系统文件协议，比如`file:///home/root/polaris.log`或者`log/polaris.log`，文件所在的路径不存在启动抛出异常。
```
[INFO] load config from polaris-server.yaml
{Bootstrap:{Logger:{OutputPaths:[log/polaris.log] ErrorOutputPaths:[] RotateOutputPath:log/polaris-server.log RotationMaxSize:500 RotationMaxAge:30 RotationMaxBackups:100 JSONEncoding:false LogGrpc:false Level:debug outputLevels: logCallers: stackTraceLevels:} StartInOrder:map[key:sz open:true] PolarisService:{EnableRegister:false ProbeAddress: Isolated:false Services:[0xc0000c6e00]}} APIServers:[{Name:httpserver Option:map[connLimit:map[maxConnLimit:5120 maxConnPerHost:128 openConnLimit:false purgeCounterExpired:5s purgeCounterInterval:10s whiteList:127.0.0.1] enablePprof:true …
```

fix: 如果OutputPaths / ErrorOutputPaths配置是本地文件，文件所在的路径不存在会抛出异常

---

.github/workflows/docker.yml
common/log/config.go

[ISSUE #154] Feat auto build dockerimage

---

go.mod
naming/instance.go
naming/server.go
naming/test/instance_test.go
store/boltdb/service.go
test/instance_test.go

[ISSUE #136] support auto create service when register instance

---

go.mod
naming/cache/service_test.go
vert.sh

fix: go.mod version uptodate

---

deploy/standalone/k8s/01-polaris-server-config.yaml

fix: update the k8s deploy config to newest

---

deploy/standalone/k8s/02-polaris-server.yaml

[ISSUE #171] fix image addr

---

store/boltdb/namespace.go
store/boltdb/service.go
store/sqldb/business.go
store/sqldb/namespace.go
store/sqldb/service.go

fix: remove all token and owner check for store

---

naming/namespace.go

fix: remove namespace owner check

---

README-zh.md
README.md

fix:fix sql link in readme

---

bootstrap/server.go
common/log/config.go
common/log/default.go
common/log/options.go
common/log/scope.go
common/log/type.go
config/config.go
deploy/standalone/k8s/01-polaris-server-config.yaml
naming/test/main_test.go
naming/testauthplugin/main_test.go
polaris-server.yaml

feat #119 
配置项
```yaml
bootstrap:
logger:
path:
naming: log/polaris-naming.log
health-check: log/polaris-health-check.log
store: log/polaris-store.log
plugin: log/polaris-plugin.log
server: log/polaris-server.log
default: log/polaris-default.log
```

[ISSUE #119] feat: multi-file log

---

.gitignore
bootstrap/server.go
common/model/naming.go
common/model/plugin_config_model.go
healthcheck/cache.go
healthcheck/check.go
healthcheck/dispatch.go
healthcheck/report.go
healthcheck/server.go
naming/cache/instance.go
naming/instance.go
naming/server.go
plugin.go
plugin/discoverevent.go
plugin/discoverevent/local/event_local.go
plugin/discoverevent/local/eventbuffer_test.go
plugin/discoverevent/local/logger.go
plugin/plugin.go
polaris-server.yaml

[ISSUE #147] feat: support instance change event

---

store/sqldb/polaris_server.sql

[ISSUE #167] docs: add mysql table construction

---

apiserver/xdsserverv3/default.go
apiserver/xdsserverv3/server.go

Xds circuit breaker

---

common/model/instance.go
common/model/naming.go
common/redispool/redis_pool.go
common/time/time.go
common/utils/time.go
go.mod
go.sum
healthcheck/server.go
naming/circuitbreaker_config.go
naming/namespace.go
naming/platform.go
naming/ratelimit_config.go
naming/routing_config.go
naming/server.go
naming/service.go
naming/service_alias.go
naming/test/main_test.go
plugin/auth/platform/platform.go
plugin/discoverstat/discoverlocal/discovercall.go
plugin/history/logger/history_logger.go
plugin/statis/local/apicall.go
store/boltdb/instance.go
store/boltdb/instance_test.go
store/sqldb/circuitbreaker_config.go
store/sqldb/default.go
store/sqldb/instance.go
store/sqldb/ratelimit_config.go
store/sqldb/routing_config.go
store/sqldb/service.go

Fixes #https://github.com/polarismesh/polaris/issues/195

feat:make Time2String as common function

---

common/utils/funcs.go
naming/circuitbreaker_config.go
naming/instance.go
naming/namespace.go
naming/platform.go
naming/ratelimit_config.go
naming/routing_config.go
naming/server.go
naming/service.go
naming/service_alias.go
test/grpc/discover.go
test/grpc/heartbeat.go
test/grpc/register.go
test/grpc/report_client.go

Fixes #https://github.com/polarismesh/polaris/issues/210

feat:Unified use utils.NewUUID()

---

common/srand/scalable_rand_test.go

Fixes # https://github.com/polarismesh/polaris/issues/208

feat:add scalable_rand test

---

README-zh.md

fix : zh install document mistake #215

---

common/redispool/redis_pool.go

fix: retry write redis when redis connect fail

---

apiserver/eurekaserver/access.go
apiserver/eurekaserver/default.go
apiserver/eurekaserver/model.go
apiserver/eurekaserver/model_test.go
apiserver/eurekaserver/server.go
apiserver/eurekaserver/worker.go
apiserver/eurekaserver/write.go
apiserver/eurekaserver/xml.go
apiserver/l5pbserver/server.go
service/l5_service.go
service/server.go

feat: 支持eureka api接入

---

service/service.go
service/service_alias.go

feat：取消创建服务的owner字段必填校验

---

.gitignore

fix: gitignore 忽略构建的包

---

.gitignore
build.sh

build.sh 新增对Darwin系统的支持

---

service/healthcheck/cache.go
service/healthcheck/dispatch.go
service/healthcheck/shardmap.go
service/healthcheck/shardmap_test.go

Fixes https://github.com/polarismesh/polaris/issues/205

feat:Use shardmap to optimize healthcheck performance

---

polaris-server.yaml

add eureka server config

---

apiserver/eurekaserver/default.go
apiserver/eurekaserver/model.go
apiserver/eurekaserver/model_test.go
apiserver/eurekaserver/server.go
apiserver/eurekaserver/worker.go
apiserver/eurekaserver/write.go
apiserver/eurekaserver/xml.go
common/log/default.go

fix: code style make eureka not working

---

bootstrap/config/config.go
bootstrap/server.go
config/test/test.yaml
polaris-server.yaml

Fixes #
polaris-server.yaml config_file rename to config

polaris-server.yaml config_file rename to config

---

.github/workflows/docker.yml
build_docker.sh
deploy/docker/prometheus/build_docker_prom.sh

[ISSUE #278] build: support push docker latest image

---

deploy/helm/templates/polaris-server-config.yaml
deploy/helm/templates/polaris-server.yaml
deploy/helm/values.yaml
deploy/standalone/k8s/01-polaris-server-config.yaml
deploy/standalone/k8s/02-polaris-server.yaml

Add xds conf

---

build_docker.sh
deploy/docker/prometheus/build_docker_prom.sh

[ISSUE #278] fix: 修复build_docker_xxx.sh脚本问题

---

config/test/bootstrap.go

Fixes https://github.com/polarismesh/polaris/issues/293

test:fix config parameter error

---

service/client.go
service/utils.go
store/sqldb/polaris_server.sql

feat: support issue #295 and #297

---

apiserver/eurekaserver/access.go
apiserver/eurekaserver/model.go
apiserver/eurekaserver/worker.go

fix: spring cloud 2020 cannot access eureka interfaces

---

polaris-server.yaml

配置中心 apiserver 开启的配置加入到 polaris-server.yaml

---

common/redispool/redis_pool.go
service/test/instance_test.go
service/test/l5service_test.go
store/boltdb/codec.go
store/boltdb/handler.go
store/boltdb/instance_test.go
store/boltdb/l5.go
store/boltdb/service_test.go
store/sqldb/service.go
test/http/instance.go
test/http/service.go

Fixes https://github.com/polarismesh/polaris/issues/223
simple fmt

style:simple fmt

---

polaris-server.yaml
tool/include

[ISSUE #321] remove stdout & stderr to ./log/stdout file

---

auth/defaultauth/group.go
auth/defaultauth/token_test.go
auth/defaultauth/user.go
store/api.go
store/auth_api.go
store/boltdb/default.go
store/boltdb/group.go
store/boltdb/group_test.go
store/boltdb/strategy.go
store/boltdb/strategy_test.go
store/boltdb/user.go
store/discover_api.go
store/sqldb/group.go

[ISSUE #319] Refactor auth

---

deploy/helm/README-zh.md
deploy/helm/README.md
deploy/helm/templates/polaris-console-config.yaml
deploy/helm/templates/polaris-namespace.yaml
deploy/helm/templates/polaris-server-config.yaml
deploy/helm/templates/polaris-server.yaml
deploy/helm/templates/prometheus.yaml
deploy/helm/values.yaml
deploy/standalone/k8s/00-polaris-console-config.yaml
deploy/standalone/k8s/01-polaris-server-config.yaml
deploy/standalone/k8s/02-polaris-server.yaml
deploy/standalone/k8s/03-prometheus.yaml
deploy/standalone/k8s/04-polaris-namespace.yaml

- [X ] Installation
Add polaris namespace for deploying in k8s.

Add polaris namespace for deploying in k8s

---

apiserver/httpserver/maintain_access.go
common/log/logger.go
common/log/options.go

支持动态修改日志等级

---

apiserver/httpserver/maintain_access.go

Fixes #346 
一般修改PUT方法，参数都是从body中获取。
从
```
curl --location --request PUT 'http://127.0.0.1:8090/maintain/v1/log/outputleve?scope=config&level=debug
```
 改为
```
curl --location --request PUT 'http://127.0.0.1:8090/maintain/v1/log/outputlevel' \
--header 'Content-Type: application/json' \
--data-raw '{
"scope": "config",
"level": "debug"
}'
```
这种方式

feat: 修改日志级别参数从body获取

---

auth/defaultauth/auth_mgn_core.go
auth/defaultauth/config.go
polaris-server.yaml

修复鉴权开关分离之后的问题

---

namespace/default.go
namespace/namespace.go
namespace/server.go

fix: 修复命名空间自动创建

---

.github/workflows/release.yml
build.sh
cache/strategy.go
common/model/client.go
deploy/helm/README-zh.md
deploy/helm/README.md
deploy/helm/templates/polaris-server-config.yaml
deploy/helm/values.yaml
deploy/standalone/k8s/01-polaris-server-config.yaml
namespace/namespace_authability.go
polaris-server.yaml
service/service.go
service/service_alias_authability.go
service/service_authability.go
store/boltdb/client.go
store/boltdb/client_test.go
store/mock/README.md

fix: kubernetes部署configmap调整 & 修复 boltdb 存储在的 clients 查询问题

---

bootstrap/server.go
common/log/config.go
common/utils/common.go
common/utils/context.go
service/batch/batch.go
service/healthcheck/check.go
service/instance.go
service/server.go
service/utils.go
store/sqldb/namespace.go
store/sqldb/service.go
store/store.go

improve readability of logging and error, func and var names, comments, logic, etc.

style: improve code readability

---

store/api.go
store/auth_api.go
store/config_file_api.go
store/discover_api.go
store/sqldb/circuitbreaker_config.go
store/sqldb/client.go
store/sqldb/common.go
store/sqldb/config_file_release.go
store/sqldb/group.go
store/sqldb/instance.go
store/sqldb/namespace.go
store/sqldb/ratelimit_config.go
store/sqldb/routing_config.go
store/sqldb/service.go
store/sqldb/strategy.go
store/sqldb/user.go

Fixes #345 
```
mysql> explain select * from service where mtime > FROM_UNIXTIME(1652286241);
+----+-------------+---------+------------+-------+---------------+-------+---------+------+------+----------+-----------------------+
| id | select_type | table   | partitions | type  | possible_keys | key   | key_len | ref  | rows | filtered | Extra                 |
+----+-------------+---------+------------+-------+---------------+-------+---------+------+------+----------+-----------------------+
|  1 | SIMPLE      | service | NULL       | range | mtime         | mtime | 4 …
```

[ISSUE #345] 依赖timestamp进行cache增量更新

---

README-zh.md
README.md

feat：修正文档说明

---

auth/defaultauth/auth_mgn_core.go
common/utils/common.go
common/utils/const.go
config/server.go
config/service/api.go
config/service/common.go
config/service/config_file.go
config/service/config_file_group.go
config/service/config_file_release.go

add operator for config module

---

config/utils/utils.go
config/utils/utils_test.go

feat: config/utils code adjust

---

common/utils/funcs.go
common/utils/stringslice_unique_test.go

refactor #https://github.com/polarismesh/polaris/issues/409

feat: refactor StringSliceDeDuplication

---

config/client_config_file.go
config/client_config_file_authibility.go
config/common.go
config/config_file.go
config/config_file_authibility.go
config/config_file_group.go
config/config_file_group_authibility.go
config/config_file_release.go
config/config_file_release_authibility.go
config/config_file_release_history.go
config/config_file_release_history_authibility.go
config/config_file_tag.go
config/server.go
config/server_authibility.go
config/watcher.go

1. refactor config/server.go
2. refactor API interface impl
3. go fmt and optimize for service

feat:refactor server init and go fmt

---

config/config_file_authibility.go

[fix] 自己掉自己的问题

---

maintain/default.go
maintain/maintain.go
maintain/maintain_authability.go
maintain/server.go
maintain/server_authability.go

refactor #https://github.com/polarismesh/polaris/issues/423

feat: maintain code adjust and default refactor

---

.github/workflows/release.yml
.github/workflows/standalone.yml
.github/workflows/testing.yml

**Please provide issue(s) of this PR: 
Fixes #42 

修改编译任务支持arm64版本打包

---

.gitignore
common/redispool/config.go
common/redispool/config_option.go
common/redispool/config_option_test.go
common/redispool/config_test.go
common/redispool/redis_pool.go

polaris-server支持redis哨兵模式和集群模式 #415 

feat: support cluster-deployed redis and sentinel-deployed redis

---

apiserver/prometheussd/server.go
plugin/discoverstat/discoverlocal/discovercall.go
plugin/discoverstat/discoverlocal/local.go
plugin/discoverstat/discoverlocal/local_test.go

…n't by `log` method.**Please provide issue(s) of this PR:**
Fixes #446 

bugfix: fix prometheus server post process callback

---

auth/auth.go
cache/cache.go
cache/circuitbreaker_config.go
cache/client.go
cache/default.go

Fixes #https://github.com/polarismesh/polaris/pull/420

feat: refactor CircuitBreakerCache and ClientCache with map + rwlock 

---

cache/instance.go

fix:fix return of empty string.

---

apiserver/eurekaserver/server.go
apiserver/httpserver/server.go
tool/include

[ISSUE #485] fix not permission when crontab run check.sh

---

apiserver/eurekaserver/config.go
apiserver/eurekaserver/server.go
apiserver/grpcserver/base.go
apiserver/httpserver/config_client_access.go
apiserver/httpserver/server.go
common/secure/config.go
common/secure/tls.go
common/utils/common.go
maintain/server_authability.go
polaris-server.yaml

feat: 通讯支持加密协议TLS

---

plugin/history/logger/history_logger.go

[ISSUE #431] polaris-history按天归档日志

---

apiserver/xdsserverv3/server.go
apiserver/xdsserverv3/server_test.go

Fixes #186
- [ X] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

[ISSUE #186] turn polaris ratelimit to envoy local ratelimit

---

apiserver/httpserver/config_console_access.go
apiserver/httpserver/config_server.go
config/api.go
config/config_file.go
config/config_file_authibility.go
config/config_file_group.go
config/config_file_test.go
store/boltdb/config_file.go
store/config_file_api.go
store/mock/api_mock.go
store/sqldb/config_file.go

add query config file by group api

---

deploy/standalone/vm/install-darwin.sh
deploy/standalone/vm/install-linux.sh
deploy/standalone/vm/install-windows.ps1

refactor: Add http_sd_configs to prometheus.yml in install.sh

---

common/log/config.go
common/log/logger.go
common/log/scope.go

refactor https://github.com/polarismesh/polaris/issues/503

feat: refactor common/log

---

apiserver/eurekaserver/server.go
apiserver/grpcserver/base.go
apiserver/httpserver/server.go
common/secure/config.go
polaris-server.yaml

Fixes #
modify tls config fields name

fix: modify the TLS configuration fields name #456

---

.github/workflows/codecov.yaml
.github/workflows/integration-testing.yml
apiserver/grpcserver/discover/server.go
apiserver/grpcserver/discover/server_test.go
polaris-server.yaml
service/instance_test.go
store/boltdb/platform.go
store/boltdb/platform_test.go
test/client_grpc_test.go
test/http/client.go
test/http/namespace.go
test/http/service.go

[ISSUE #512] fix get services not update pb cache in SDK interface

---

.github/workflows/codecov.yaml
plugin/healthchecker/heartbeatmemory/checker_memory.go
plugin/healthchecker/heartbeatmemory/checker_memory_test.go

[ISSUE #520] hot fix issue #520 into release-v1.10.0

---

build_docker.sh

Build docker

---

.github/workflows/docker.yml
.github/workflows/integration-testing-mysql.yml
.github/workflows/integration-testing.yml
.github/workflows/release.yml
Makefile
README-zh.md
README.md
build_docker.sh

Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Fixes #539

build: use Makefile to build Polaris instead of `build.sh`

---

deploy/standalone/vm/uninstall-windows.ps1

fix: fix windown uninstall.bat

---

deploy/standalone/vm/install-windows.bat
deploy/standalone/vm/uninstall-windows.bat
deploy/standalone/vm/uninstall-windows.ps1

Hotfix uninstall.sh

---

apiserver/httpserver/handler.go
go.mod
go.sum
service/ratelimit_config.go

feat: 合入增量的限流功能修改

---

.github/workflows/docker-standalone.yml
.github/workflows/docker.yml
.gitignore
Dockerfile
build_docker.sh
deploy/docker/prometheus/build_docker_prom.sh
deploy/standalone/vm/Dockerfile

feat: fix docker arm64 image support

---

service/instance.go

feat:支持修改实例时修改地理位置信息

---

deploy/docker/prometheus/prometheus.yml

fix: fix docker prometheus

---

config/config_file_tag_test.go
polaris-server.yaml
service/instance.go
service/service.go
store/boltdb/default.go

fix:修复v1.11.0的问题

---

config/config_file_tag_test.go
deploy/docker/prometheus/prometheus.yml
polaris-server.yaml
service/service.go
store/boltdb/default.go

Fix delete service check ratelimit

---

deploy/standalone/vm/install-darwin.sh
deploy/standalone/vm/install-linux.sh

fix: fix standalone install can't modify port

---

apiserver/xdsserverv3/cluster.go
apiserver/xdsserverv3/configurations.go
apiserver/xdsserverv3/dump.go
apiserver/xdsserverv3/listener.go
apiserver/xdsserverv3/server.go
apiserver/xdsserverv3/server_test.go
apiserver/xdsserverv3/testdata/data.json
apiserver/xdsserverv3/testdata/dump.yaml
apiserver/xdsserverv3/testdata/permissive.dump.yaml
apiserver/xdsserverv3/testdata/strict.dump.yaml
deploy/helm/templates/polaris-server-config.yaml
deploy/helm/templates/polaris-server.yaml

feat: xdsserver support mtls mode

---

cache/instance.go
cache/instance_test.go
go.mod
go.sum
service/instance_test.go
store/boltdb/circuitbreaker.go
store/boltdb/namespace.go
store/boltdb/namespace_test.go
store/boltdb/ratelimit.go
store/boltdb/routing.go

fix: fix issue #573 & #596

---

go.mod

grouping mod dependencies

---

deploy/standalone/vm/install-linux.sh

Fixes #594 使用docker安装polaris-server-standalone，重启容器后新建的数据被清空

fix: docker standalone方式启动 重启后数据被清空

---

build.sh

feat: 将store/sqldb 下的scripts一并进行打包

---

auth/defaultauth/user.go
auth/defaultauth/utils.go
common/utils/common.go
polaris-server.yaml
service/instance.go
store/boltdb/default.go
store/boltdb/group.go
store/boltdb/strategy.go
store/boltdb/user.go

fix:issue #644

---

apiserver/httpserver/handler.go

fix: invalid memory address or nil pointer dereference

---

common/model/naming.go
common/model/naming_test.go
service/main_test.go
service/ratelimit_config.go

fix：支持限流规则无法彻底删除的问题

---

bootstrap/server.go

bootstrap config pretty print

---

apiserver/httpserver/auth.go
apiserver/httpserver/auth_apidoc.go
apiserver/httpserver/auth_apinotes.go
apiserver/httpserver/config_server_apidoc.go
apiserver/httpserver/swagger_access.go
go.mod
go.sum

添加鉴权模块相关接口文档

---

apiserver/httpserver/core_console_access.go
apiserver/httpserver/core_console_apidoc.go
apiserver/httpserver/core_console_apinotes.go

丰富core下面namespace相关接口的swagger信息

---

store/sqldb/scripts/delta/v1_8_0-v1_11_0.sql

[sql script]remove charset and collate,use default

remove auto_increment=1,remove charset and collate

---

cache/cache.go
cache/routing_config.go
cache/routing_config_bucket.go
service/routing_config_v1_test.go
service/routing_config_v1tov2.go
service/routing_config_v2.go
testdata/service_test_sqldb.yaml

Fix issue 625 ci

---

.github/workflows/integration-testing-mysql.yml
apiserver/xdsserverv3/server.go
cache/routing_config.go
cache/routing_config_bucket.go
common/log/type.go
polaris-server.yaml
testdata/service_test_sqldb.yaml

fix:修复自定义路由v1转v2的id漂移问题

---

.github/workflows/integration-testing-mysql.yml
apiserver/xdsserverv3/server.go
cache/routing_config.go
cache/routing_config_bucket.go
common/log/type.go
common/routing/routing.go
common/utils/funcs.go
polaris-server.yaml
service/routing_config_v1_test.go
service/routing_config_v1tov2.go
store/boltdb/routing_config_v2.go
testdata/service_test_sqldb.yaml

Fix ci error

---

apiserver/eurekaserver/eureka_suit_test.go
apiserver/xdsserverv3/callback.go
apiserver/xdsserverv3/server.go
auth/defaultauth/auth_mgn_core_test.go
auth/defaultauth/group_test.go
auth/defaultauth/strategy_test.go
auth/defaultauth/user_test.go
cache/cache_test.go
cache/default.go
cache/test_export.go
common/model/v2/routing.go
common/routing/routing.go
config/bootstrap_test.go
deploy/standalone/vm/install-linux.sh
service/main_test.go
service/routing_config_v1tov2.go
service/service_alias_test.go
testdata/service_test_sqldb.yaml

Refactor xdsv3 log

---

.github/workflows/standalone.yml
.gitignore
apiserver/xdsserverv3/callback.go
bootstrap/server.go
cache/default.go
cache/test_export.go
deploy/helm/templates/polaris-limiter-config.yaml
deploy/helm/templates/polaris-limiter.yaml
deploy/helm/values.yaml
deploy/standalone/docker-compose/docker-compose.yaml
deploy/standalone/docker-compose/limiter/polaris-limiter.yaml
deploy/standalone/docker-compose/server/polaris-server.yaml
deploy/standalone/k8s/05-polaris-limiter.yaml
deploy/standalone/k8s/06-polaris-limiter-config.yaml
service/main_test.go
service/routing_config_v1_test.go
service/routing_config_v2_test.go
testdata/service_test_sqldb.yaml

Feat limiter deploy

---

apiserver/apiserver.go
apiserver/prometheussd/prometheus_access.go
auth/api.go
bootstrap/server.go
cache/instance.go
cache/service.go
cache/service_test.go
cache/store_time.go
cmd/start.go
namespace/namespace.go
service/client.go
service/healthcheck/server.go
store/api.go
store/boltdb/tool.go
store/sqldb/tool.go

perf(annotate): 优化代码注释内容

---

.github/workflows/codecov.yaml
.github/workflows/integration-testing-mysql.yml
cache/routing_config.go
cache/routing_config_bucket.go
common/routing/routing.go
polaris-server.yaml
service/routing_config_v1.go
service/routing_config_v1tov2.go
service/routing_config_v2.go
service/routing_config_v2_test.go
store/sqldb/scripts/polaris_server.sql
test/client_grpc_test.go
test/grpc/register.go
testdata/polaris-server.yaml

fix issue #694

---

cache/routing_config_query.go

fix: issue 701

---

deploy/helm/templates/polaris-limiter.yaml
deploy/helm/templates/polaris-server-config.yaml
deploy/standalone/k8s/02-polaris-server-config.yaml
deploy/standalone/k8s/05-polaris-limiter.yaml

fix:修复polaris-limiter 容器部署失败问题

---

deploy/helm/templates/polaris-console-config.yaml
deploy/helm/templates/polaris-limiter.yaml
deploy/helm/templates/polaris-server-config.yaml
deploy/standalone/docker-compose/console/polaris-console.yaml
deploy/standalone/k8s/02-polaris-server-config.yaml
deploy/standalone/k8s/05-polaris-limiter.yaml

fix:修复polaris-console.yaml问题

---

deploy/helm/templates/polaris-server.yaml

fix: 修复polaris-console.yaml问题

---

deploy/helm/templates/polaris-limiter.yaml
deploy/helm/templates/polaris-server.yaml

fix: 修复polaris-console.yaml启动问题

---

go.mod
go.sum

Fixes #https://github.com/polarismesh/polaris/issues/729
update go.mod for require

feat: update go.mod for require

---

namespace/default.go
namespace/namespace.go
namespace/namespace_authability.go
namespace/server.go
namespace/server_authability.go
namespace/test_export.go
plugin/auth.go
plugin/auth/defaultauth/auth.go
plugin/auth/defaultauth/default.go
plugin/auth/platform/platform.go
plugin/cmdb/memory/memory.go
plugin/discoverevent.go
plugin/discoverevent/local/event_local.go
plugin/discoverevent/loki/event_loki.go
plugin/discoverevent/loki/event_loki_test.go
plugin/discoverevent/loki/logger.go
plugin/discoverstatis.go
plugin/history.go
plugin/history/loki/history_loki.go
plugin/history/loki/history_loki_test.go
plugin/history/loki/logger.go
plugin/password.go
plugin/plugin.go
plugin/ratelimit.go
plugin/ratelimit/lrurate/base.go
plugin/ratelimit/lrurate/lrurate.go
plugin/ratelimit/token/api_limit.go
plugin/statis.go
plugin/statis/local/common.go
plugin/statis/local/local.go

Fixes https://github.com/polarismesh/polaris/issues/734
update plugin for code style

feat: update plugin for code style

---

deploy/helm/templates/polaris-server-config.yaml
deploy/standalone/docker-compose/server/polaris-server.yaml
deploy/standalone/k8s/02-polaris-server-config.yaml

[ISSUE #737] fix:修复polaris-server.yaml

---

apiserver/httpserver/maintain_access.go
apiserver/httpserver/maintain_apidoc.go
apiserver/httpserver/maintain_apinotes.go
apiserver/httpserver/swagger_access.go
go.mod
go.sum

feat: 丰富运维管理接口相关接口swagger信息

---

bootstrap/run_darwin.go
bootstrap/run_linux.go
bootstrap/run_windows.go
bootstrap/server.go

Fixes https://github.com/polarismesh/polaris/issues/769
fix server exit or restart signal

feat: fix server exit or restart signal

---

cache/cache.go
cache/config_file.go
cache/config_file_bucket.go
cache/config_file_test.go
cache/instance.go
cache/l5.go
cache/namespace.go
cache/ratelimit_config.go
cache/routing_config.go
cache/routing_config_bucket.go
cache/routing_config_query.go
cache/service.go
cache/service_query.go
cache/strategy.go
cache/user.go
config/server_authability.go

Fixes https://github.com/polarismesh/polaris/issues/774
code style for cache package

feat: code style for cache package

---

common/timewheel/timewheel.go
common/timewheel/timewheel_test.go

fix: #751 timewheel用来做轮转任务会每轮增加timewheel.interval时间的问题

---

apiserver/httpserver/swagger_access.go
apiserver/httpserver/v1/naming_client_access.go
apiserver/httpserver/v1/naming_client_access_apidoc.go
apiserver/httpserver/v1/naming_client_access_apinotes.go
apiserver/httpserver/v1/naming_console_access.go
apiserver/httpserver/v1/naming_console_access_apidoc.go
apiserver/httpserver/v1/naming_console_access_apinotes.go
apiserver/httpserver/v2/naming_client_access.go
apiserver/httpserver/v2/naming_console_access.go
apiserver/httpserver/v2/naming_console_access_apidoc.go
apiserver/httpserver/v2/naming_console_access_apinotes.go

enrich naming swagger docs

---

deploy/standalone/vm/install-windows.ps1

修复：windows中修改端口后无效的问题

---

.golangci.yml

fix gilangci config

---

README-zh.md
README.md

docs: 修复 README 中失效的链接

---

README-zh.md
README.md

docs: 修复图片链接失效

---

bootstrap/server.go
common/eventhub/const.go
common/eventhub/eventhub.go
common/eventhub/eventhub_test.go
common/eventhub/subscription.go
common/eventhub/subscription_test.go
common/eventhub/topic.go
common/eventhub/topic_test.go
plugin/discoverevent/local/event_local.go
service/healthcheck/server.go
service/healthcheck/test_export.go
service/main_test.go
service/server.go

* fix issue (#342)
* 增加事件中心逻辑
* discoverevent通过事件中心发布订阅

feat: 北极星内部事件中心机制优化(#342)

---

test/uplower_test.go

支持 eureka 服务大小写不敏感在北极星的存储方式,调整集成测试。

---

apiserver/httpserver/auth.go
apiserver/httpserver/auth_apinotes.go
auth/api.go
auth/defaultauth/server.go
common/api/v1/auth_response.go

typo: 替换错别字

---

.github/workflows/standalone.yml
apiserver/eurekaserver/access.go
apiserver/eurekaserver/applications.go
apiserver/eurekaserver/applications_test.go
apiserver/eurekaserver/replicate.go
apiserver/eurekaserver/server.go
apiserver/eurekaserver/tool.go
apiserver/eurekaserver/vip.go
apiserver/eurekaserver/write.go
polaris-server.yaml

* feat: 支持eureka双向数据同步
* fix：golintci warnings
* feat: 调整import顺序
* fix：修复golint格式化问题
* fix：修复导入问题
* fix: 修复导入顺序问题
* Fix k8s deploy (#819)
* fix issue #629 (#693)
* docs:优化错误信息描述
* Update zh.toml
* fix:修复eureka心跳协议错误码不兼容问题
* fix:修复eureka心跳协议错误码不兼容问题
* unit:添加单元测试
* test:调整测试配置文件位置
* fix:issue #692
* fix:issue #692
* fix:issue #692
* fix:issue #692
* docs:add error code desc
* fix:调整license-checker的触发
* fix:调整license-checker的触发
* fix:k8s standalone deploy
* feat：优化大小写问题，eureka插件默认大小写不敏感，无需配置
* feat：读取的时候进行大写转换
* feat：修改读取时候大小写
* feat：处理replication大小写
* fix：修复用例失败问题
* fix：修复用例失败问题
Co-authored-by: liaochuntao <liaochuntao@live.com>
Fixes # …

feat：优化eureka插件大小写敏感，默认大小写不敏感 (#820)

---

apiserver/eurekaserver/access.go
apiserver/eurekaserver/replicate.go

feat：修复polaris之间走eureka同步接口出现报错的问题

---

apiserver/eurekaserver/access.go
apiserver/eurekaserver/replicate.go

fix: eureka同步时，实例不存在没有返回404，导致eureka触发不了重注册

---

service/healthcheck/cache.go

fix_client_check

---

deploy/standalone/vm/uninstall-windows.bat
polaris-server.yaml

Release v1.13.0

---

standalone/docker-compose/docker-compose.yaml

解决docker-compose单机版的配置问题

---

store/sqldb/instance.go

fix:实例重注册问题修复

---

release/standalone/linux/install.sh

fix install.sh

---

deploy/standalone/vm/install-linux.sh
store/sqldb/config_file_group.go

fix:install prometheus and npe

---

apiserver/eurekaserver/applications.go
apiserver/eurekaserver/applications_test.go
apiserver/eurekaserver/config.go
apiserver/eurekaserver/log.go
apiserver/eurekaserver/server.go

fix：去掉故障兜底能力 & 增加自定义dci的功能

---

go.mod
go.sum

feat: upgrade specification to 1.1.0 stable release

---

release/cluster/kubernetes/06-polaris-limiter-config.yaml

[ISSUE #927]修正06-polaris-limiter-config.yaml中默认polaris服务地址

---

service/instance_test.go

添加测试用例，支持指定 instance id

---

release/standalone/docker-compose/docker-compose.yaml
release/standalone/docker-compose/mysql/Dockerfile

Docker compose 升级 mysql 8

---

service/healthcheck/server.go

fix req.metadata map nil

---

cache/instance.go
release/standalone/build_standalone_docker.sh

logs:添加缓存模块的相关日志

---

plugin/discoverevent.go
plugin/history.go
plugin/plugin.go

fix:修复单机版本镜像

---

apiserver/eurekaserver/access.go

ContentType更合理一些（其实是为了兼容已经在使用的非java客户端）

---

plugin/healthchecker/heartbeatmemory/checker_memory.go
plugin/healthchecker/heartbeatredis/checker_redis.go
service/healthcheck/check.go
service/healthcheck/server.go
service/healthcheck/test_export.go
service/instance_test.go
service/main_test.go
service/test_common.go

query unhealth instance

---

apiserver/eurekaserver/write.go

调整leaseInfo为nil时的心跳参数处理逻辑与eureka server一致

---

apiserver/eurekaserver/write.go
common/model/metadata.go
common/redispool/pool.go
common/redispool/redis_pool.go
plugin/healthchecker.go
plugin/healthchecker/heartbeatmemory/checker_memory.go
plugin/healthchecker/heartbeatredis/checker_redis.go
plugin/healthchecker/heartbeatredis/checker_redis_test.go
service/healthcheck/config.go
service/healthcheck/dispatch.go
service/healthcheck/server.go
service/healthcheck/test_export.go
service/instance_check_test.go

feat: 支持当北极星服务端全下线并恢复后，等待3TTL后再重启check任务 (#5)

---

service/client_v1.go

[ISSUE #1015] 修复熔断探测规则下发可能导致客户端刷日志的问题

---

service/ratelimit_config.go

[ISSUE #996] Remove unused code

---

apiserver/eurekaserver/write.go
common/model/metadata.go
common/redispool/pool.go
common/redispool/redis_pool.go
plugin/healthchecker.go
plugin/healthchecker/heartbeatmemory/checker_memory.go
plugin/healthchecker/heartbeatredis/checker_redis.go
plugin/healthchecker/heartbeatredis/checker_redis_test.go
service/healthcheck/config.go
service/healthcheck/dispatch.go
service/healthcheck/server.go
service/healthcheck/test_export.go
service/instance_check_test.go

feat: 支持当北极星服务端全下线并恢复后，等待3TTL后再重启check任务 (#5) (#1008)

---

apiserver/eurekaserver/write.go

fix:修复构建失败问题

---

apiserver/eurekaserver/write.go
plugin/statis/base/apicall.go

fix:修复map并发读写问题

---

apiserver/eurekaserver/access.go

format vip

---

apiserver/httpserver/http/handler.go
go.mod
go.sum
maintain/job/config.go
maintain/job/job.go
release/conf/polaris-server.yaml
test/integrate/resource/config_center.go

修复有子目录的配置文件无法导入问题

---

apiserver/eurekaserver/eureka_suit_test.go
apiserver/eurekaserver/write_test.go
service/healthcheck/test_export.go
service/instance_check_test.go
test/suit/test_suit.go

test: add polaris.checker health check unit test

---

apiserver/xdsserverv3/node.go
common/model/routing.go
release/conf/polaris-server.yaml

fix:修复sidecar无法获取到xds规则

---

apiserver/eurekaserver/access.go
apiserver/eurekaserver/access_test.go
apiserver/eurekaserver/delta_worker.go
apiserver/eurekaserver/model.go
apiserver/eurekaserver/replicate.go
apiserver/eurekaserver/replicate_test.go
apiserver/eurekaserver/replicate_worker.go
apiserver/eurekaserver/server.go
apiserver/eurekaserver/server_test.go
apiserver/eurekaserver/tool.go
apiserver/eurekaserver/write.go
apiserver/eurekaserver/write_test.go

feat: eureka注册发现支持命名空间隔离

---

release/conf/polaris-server.yaml
store/boltdb/circuitbreaker_rule.go

 fix:修复熔断规则编辑后创建时间被重置

---

release/standalone/windows/run-windows.ps1
release/standalone/windows/run.bat
release/standalone/windows/stop-windows.ps1
release/standalone/windows/stop.bat

添加windows启动停止脚本

---

release/standalone/build_standalone_docker.sh

fix: remove shell

---

release/conf/polaris-server.yaml
store/mysql/ratelimit_config.go

fix:修复限流规则修改服务信息时下发失败问题

---

release/conf/polaris-server.yaml
release/standalone/build_standalone_docker.sh
store/mysql/ratelimit_config.go

install:修复单机镜像脚本问题

---

apiserver/eurekaserver/replicate.go
apiserver/grpcserver/discover/v1/client_access.go
common/batchjob/batch.go
common/batchjob/batch_test.go
common/batchjob/future.go
common/eventhub/subscription.go
plugin/healthchecker/leader/beat_cache.go
plugin/healthchecker/leader/checker_leader.go
plugin/healthchecker/leader/checker_leader_test.go
plugin/healthchecker/leader/config.go
plugin/healthchecker/leader/peer.go
release/conf/polaris-server.yaml

fix:BatchController occasionally gets stuck when the check leader occurs

---

common/batchjob/batch.go
common/batchjob/batch_test.go
common/batchjob/future.go
common/eventhub/eventhub.go
common/eventhub/test_export.go
plugin/healthchecker/leader/checker_leader.go
plugin/healthchecker/leader/checker_leader_test.go
plugin/healthchecker/leader/peer.go
plugin/healthchecker/leader/peer_test.go
store/mysql/admin.go

refactor:调整checker_leader中batchjob的使用

---

apiserver/grpcserver/discover/v1/heartbeat_access.go
common/batchjob/batch.go
common/batchjob/batch_test.go
common/batchjob/future.go
plugin/healthchecker.go
plugin/healthchecker/leader/checker_leader.go
plugin/healthchecker/leader/peer.go
plugin/healthchecker/memory/checker_memory.go
plugin/healthchecker/memory/checker_memory_test.go
plugin/healthchecker/redis/checker_redis.go
plugin/healthchecker/redis/checker_redis_test.go
service/healthcheck/client.go
service/healthcheck/report.go
service/healthcheck/server.go

refactor:peer的执行方法使用Future.DoneTimeout

---

apiserver/grpcserver/discover/v1/heartbeat_access.go
common/batchjob/batch.go
plugin/healthchecker.go
plugin/healthchecker/leader/checker_leader.go
plugin/healthchecker/leader/peer.go
plugin/healthchecker/memory/checker_memory.go
plugin/healthchecker/redis/checker_redis.go
service/healthcheck/server.go

fix:修复batchjob.GracefulStop 卡死问题

---

common/batchjob/batch_test.go
common/batchjob/future.go
plugin/healthchecker/leader/peer.go

fix:peer close not exec cause memory leak

---

common/batchjob/batch.go
common/batchjob/future.go
common/metrics/sys_metrics.go
common/metrics/types.go
plugin/healthchecker/leader/checker_leader.go
plugin/healthchecker/leader/metrics.go
plugin/healthchecker/leader/peer.go
store/mysql/instance.go
store/mysql/service.go

perf:leader checker use more grpc.Conn to improve heartbeat tps and reduce rts

---

cache/instance_metrics.go
common/batchjob/batch_test.go
common/batchjob/future.go
plugin/healthchecker/leader/checker_leader.go
plugin/healthchecker/leader/metrics.go
plugin/healthchecker/leader/peer.go

fix:offline service count bug

---

cache/instance_metrics.go
common/batchjob/batch.go
common/batchjob/batch_test.go
common/batchjob/future.go
plugin/healthchecker/leader/checker_leader.go
plugin/healthchecker/leader/config.go
plugin/healthchecker/leader/metrics.go
plugin/healthchecker/leader/peer.go

fix:use grpc stream send msg in concurrently

---

apiserver/xdsserverv3/server_test.go
maintain/job/clean_deleted_instance.go
maintain/job/delete_empty_service.go
maintain/job/delete_unhealthy_instance.go
maintain/job/job.go
maintain/maintain.go
release/cluster/helm/templates/config-polaris-server.yaml
release/cluster/kubernetes/02-polaris-server-config.yaml
release/conf/polaris-server.yaml
release/standalone/docker-compose/server/polaris-server.yaml
store/boltdb/maintain.go
store/boltdb/maintain_test.go
store/maintain_api.go
store/mock/api_mock.go
store/mysql/maintain.go

[ISSUE #1113] 修复清理软删除实例可能导致缓存更新不正确的问题

---

apiserver/grpcserver/config/client_access.go
apiserver/grpcserver/config/server.go
auth/defaultauth/auth_checker_test.go
common/api/v1/config_file_response_build.go
config/api.go
config/client_config_file.go
config/client_config_file_authibility.go
config/client_test.go
config/config_file_test.go
config/server_authability.go
go.mod
go.sum
import-format.sh

Fixes # https://github.com/polarismesh/polaris/issues/1134

Add support for config upsert and publish

---

store/discover_api.go

doc：CircuitBreakerStore文档注释错误

---

apiserver/httpserver/docs/admin_apidoc.go
apiserver/httpserver/docs/admin_apinotes.go
apiserver/httpserver/docs/auth_apinotes.go
apiserver/httpserver/docs/client.go
apiserver/httpserver/docs/config_server_apidoc.go
apiserver/httpserver/docs/instance.go
apiserver/httpserver/docs/namespace.go
apiserver/httpserver/docs/naming_client_access_apidoc.go
apiserver/httpserver/docs/service.go

docs(update): 完善OpenAPI swagger 文档

---

.github/workflows/golangci-lint.yml
CONTRIBUTING.md
apiserver/eurekaserver/model.go
apiserver/httpserver/auth.go
apiserver/httpserver/config_server.go
apiserver/httpserver/docs/client.go
common/model/config_file.go
config/client_config_file.go
config/client_config_file_authibility.go
config/client_test.go
config/config_file.go
config/config_file_group.go
config/config_file_release.go
config/config_file_release_authibility.go
config/config_file_release_history.go
config/config_file_tag.go
config/config_file_template.go
config/config_file_template_authibility.go
config/connection_manager.go
config/server.go
config/server_authability.go
config/utils.go
config/utils_test.go
config/watcher.go
release/conf/i18n/en.toml
store/boltdb/config_file_tag.go

[refactor] optimize the code style of the configuration center

---

apiserver/eurekaserver/replicate.go
apiserver/eurekaserver/write.go

eureka instanceid兼容

---

apiserver/xdsserverv3/resource/help.go
apiserver/xdsserverv3/resource/model.go
apiserver/xdsserverv3/server.go
apiserver/xdsserverv3/v1/cluster.go
apiserver/xdsserverv3/v2/cds.go
test/outlier/README.md
test/outlier/backend/Dockerfile
test/outlier/backend/main.go
test/outlier/build.sh
test/outlier/frontend/Dockerfile
test/outlier/frontend/main.go
test/outlier/outlier.yaml

feat(xds): add OutlierDetection and HealthCheck

---

apiserver/eurekaserver/replicate.go
apiserver/eurekaserver/write.go

调整与Eureka实例的状态兼容逻辑

---

auth/defaultauth/auth_checker.go
auth/defaultauth/utils.go
auth/defaultauth/utils_test.go

Fixes #
1. 用户组 token 鉴权 bug 修复
2. 用户名校验规则修改：允许包含英文句号

用户组token鉴权bug修复；用户名校验规则修改：允许包含英文句号

---

apiserver/grpcserver/base.go

fix:panic 添加日志打印

---

.github/workflows/release.yml
apiserver/grpcserver/base.go

fix: replace github release upload action

---

.github/workflows/release.yml
apiserver/grpcserver/base.go
store/mysql/scripts/delta/v1_17_0-v1_17_3.sql

action: upgrade github release publisher action yaml define

---

.github/workflows/release.yml
apiserver/grpcserver/base.go
store/mysql/scripts/delta/v1_17_0-v1_17_3.sql

 fix:panic 添加日志打印

---

store/mysql/config_file_release_history.go

fix:修复配置历史兼容查询问题

---

apiserver/xdsserverv3/resource/node.go
config/config_file_group.go
store/mysql/admin.go

fix:修复查询配置文件分组列表不显示文件数量

---

apiserver/grpcserver/cache.go
apiserver/httpserver/server.go
apiserver/httpserver/utils/cache.go
apiserver/httpserver/utils/handler.go
release/conf/polaris-server.yaml

…essing of service discovery QPS when using api-http server
Fixes #1234

in order to improve the processing of service discovery QPS when using api-http server

---

cache/api/types.go

fix typo: firtstUpdate -> firstUpdate

---

cache/config/config_file.go
common/conn/limit/listener.go
common/utils/collection.go
config/config_file_release.go
config/server.go
release/cluster/helm/templates/config-polaris-server.yaml
release/cluster/kubernetes/02-polaris-server-config.yaml
release/standalone/docker-compose/server/polaris-server.yaml
store/boltdb/config_file_release.go
store/mysql/scripts/delta/v1_17_0-v1_17_3.sql

fix:修复配置版本列表查询问题

---

apiserver/xdsserverv3/resource/help.go
store/mysql/scripts/delta/v1_17_0-v1_17_3.sql

fix:修复增量SQL语句不对问题

---

apiserver/eurekaserver/delta_worker.go

增强eureka delta api的稳定性

---

apiserver/xdsserverv3/resource/help.go
store/mysql/scripts/delta/v1_17_0-v1_17_3.sql

fix:修复xds下发限流匹配规则有问题

---

config/config_chain.go
config/config_file.go

fix:configuration of enabling encryption did not return the correct fields.
Fixes #

fix:configuration of enabling encryption did not return the correct fields.

---

common/utils/collection.go
config/watcher.go

fix:change file will not notify to client

---

common/utils/collection.go
common/utils/collection_test.go

fix:clean config watch connection will hang server

---

store/boltdb/config_file_release_history.go
store/mysql/config_file_release_history.go

fix release_history search bug

---

apiserver/httpserver/server.go

Fixes #
post 在不支持的请求类型中，也不用上报，减少上报指标统计维度&数量

fix:无效请求不需要上报prometheus

---

apiserver/grpcserver/discover/v1/client_access.go
common/utils/funcs.go

Fixes [#201](https://github.com/polarismesh/polaris-go/issues/201)

feat: extract token from grpc meta header

---

store/boltdb/load.go

fix: close loadFile

---

release/README.md

Fix English document links

---

store/mysql/scripts/polaris_server.sql

fix: 修改polaris_server.sql中的语法错误
